### ISSUE TITLE
web surfing very slow

### ISSUE THREAD

**Issue by enzino80** [easyphp/easyphp-devserver#102]
Hello, when I try surfing on backend or in frontend, it takes some seconds to change page. Please could you advice a procedure for improving the devserver speed?

Thanks

**Comment by Feyornowa** [comment]
Same here.
Checked httpd.conf. All seems OK.
Not described how PHP is run.

**Comment by mistert209** [comment]
The cause of this problem is IPv4 vs IPv6 and therefore itś not an EasyPHP issue.
As of Windows 7 localhost resolution is no longer don via the host file but via an internal DNS resolver.

So basicaly you try to connect to MySQL via localhost, the DNS resolvers first tries IPv6... times out and falls back to IPv4.

There are a few way to fix this. For beginners I recommend to connect to 127.0.0.1 instead of localhost. Google has the answer if you want to fix this "problem" on more fancy ways

good luck
