### ISSUE TITLE
Devserver 17 Nginx 1.12.0 is not autostarting

### ISSUE THREAD

**Issue by piotrmocko** [easyphp/easyphp-devserver#127]
When I open EasyPHP Dashboard then I can start Nginx, 
but setting an option to autostart it during launch does not work. 
Saving settings is adding to eds.ini Autostart_httpserver=1.
But when I start Devserver as Administrator, only MySQL is starting and I have to start Nginx manually.

**Comment by margenn** [comment]
This problem occur only on command-line mode (run-devserver.exe), from dashboard, nginx starts as expected.

After debugging a while, I came to this workaround:

Edit this file: .....\eds-binaries\httpserver\nginx[version]_[timestamp]\eds-app-start.php

Add the following line, right before the line starting with "..... exec('cd "..\eds-binaries\httpserver ....":

`if (empty($_SERVER["DOCUMENT_ROOT"])) { $_SERVER["DOCUMENT_ROOT"] = realpath(__DIR__ . '/../../..') . '\\eds-dashboard\\'; }`

This problem occurs, because the variable $_SERVER["DOCUMENT_ROOT"] exists only on web-mode (dashboard). When running php code from command-line (or menu) you need to recriate it, so that the file eds-app-launch.exe can be found.

Tip: To dump all variables to a file, I used this command:
`$myfile = fopen("debug.txt", "a"); fwrite($myfile, (print_r(get_defined_vars(), true)) . "\n"); fclose($myfile);`
