### ISSUE TITLE
easyphp dev server 17.0 unusable with windows-10

### ISSUE THREAD

**Issue by fichant307** [easyphp/easyphp-devserver#197]
Easyphp devserver 17.0 absolutely does not work with windows 10.
After loading from www.easyphp.org, it is impossible to launch this program without getting the following message: "the code execution cannot proceed because msvcr110.dll was not found."
The products on my computer are:
-Easyphp devserver 17.0 "wesley village"  run-devserver.exe : 1.6.2.37
-Windows 10 version 1903    system version 18362.657
-Microsoft visual C++ redistribuable (X86) version 14.023026
The products have been installed, reinstalled and nothing has changed. Easyphp has become unusable.

**Comment by webitman** [comment]
Look here
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
Download version 17 and install en reboot server.

**Comment by laurentabbal** [comment]
Devserver works just fine on Windows 10. For your error, please read the FAQ :https://www.easyphp.org/faq_devserver.php

**Comment by fichant307** [comment]
Great help but ... not working 

Envoyé de mon iPhone

> Le 16 févr. 2020 à 09:26, Laurent Abbal <notifications@github.com> a écrit :
> 

﻿
Devserver works just fine on Windows 10. For your error, please read the FAQ :https://www.easyphp.org/faq_devserver.php

**Comment by yawn-g** [comment]
The FAQ should say "use xampp instead" because that's what I did and it works

**Comment by fichant307** [comment]
I'm sorry but none of the proposed solutions work. Why not clearly indicate the version of the redistributable visual basic and its installation procedure? I will now test XAMPP.

**Comment by yawn-g** [comment]
I had no issue with XAMPP, unlike Easyphp it works with Newer versions of Visual C++.

NOTE TO "Repository owner": if you want Easyphp to be as successful as it used to be, maybe you should pay attention to criticism instead of closing threads after pointing to a FAQ that doesn't solve the problems raised. XAMPP works with Win 10 and Visual C++ 2017, unlike Easyphp. Please read your FAQ and update it if there's a way to make it work.
