### ISSUE TITLE
Devserver stops automatically

### ISSUE THREAD

**Issue by mnabialek** [easyphp/easyphp-devserver#22]
I click **open dashboard**, then I start web server and php. I then run `127.0.0.1/phpinfo.php` so server is working, now I click again **open dashboard** and I see no web server and no mysql is running and when I go again to `127.0.0.1/phpinfo.php` I see it's not working any more

**Comment by StaggerLeee** [comment]
I am sorry, you can delete this issue:
https://github.com/easyphp/easyphp-devserver/issues/26

I have not checked old issues.

-----------------------------------

I have same problem. Never mind what browser is default.
Will copy my comment from this issue so you can delete it, or merge.

---------------------------

When I click on Icon to open dashboard both Apache and mySql deactivate. It is not just something visual inside Dashboard (green icons), servers are disabled for real. It happened several time tills now.

I made Chrome browser as default browser because I dont use Edge.

Dont know if services are disabled by "kill" or "shutdown". Judging by how fast it happens it is "kill".
Now, many Users use innoDB databases. And soon or later it will end with corrupted and non recoverable databases.

**Comment by StaggerLeee** [comment]
I made Chrome Bookmark for Dashboard. Will not touch starter icon untill it is fixed. 
It is some Windows thing. Server error logs cannot say anything about it, except that servers was shutdown unnaturally.

**Comment by easyphp** [comment]
Hi
It will be fixed with the next version. If you want a workaround see #28.

**Comment by StaggerLeee** [comment]
It wont help. We can make default browsers in Windows 10.

I tried with Edge and Chrome, They both end server processes when Dashboard opens,

**Comment by easyphp** [comment]
Hi. 
See the last comment of the issue #28. Copy the attached file and use "Run Dashboard".
